[rollout] fix: error in __collect_lora_params() in FSDPVLLMShardingManager (#1909)
### What does this PR do?

> Fix bug on DAPO lora training, based on currently main branch, the
entrance file is recipe/dapo/test_dapo_7b_math_lora.sh

### Specific Changes

> Just 2 line code fix as explain in the "Test" module below

### Usage Example
adds actor_rollout_ref.model.lora_rank=8 \ into the
"recipe/dapo/test_dapo_7b_math_lora.sh" file to enable lora RL training.

```bash
bash recipe/dapo/test_dapo_7b_math_lora.sh
```

### Test
a test .sh file: recipe/dapo/test_dapo_7b_math_lora.sh to test dapo with
lora training.

Before this change, the training have the error

> TypeError: argument of type 'torch.device' is not iterable in the line
code below
orig_dev = "cpu" if "cpu" in next(model.parameters()).device else "cuda"

This error is caused the string "cpu" is not in the class "torch.device"
which is not a string or not iterable.

After this change, the lora RL training starts normally.

---------

Co-authored-by: qichang.dong <dongqichang@ecmas.ai>